#Kotlin
kotlin.code.style=official
#Kotlin-NeiCunFenPeiHuanJingBianLiang, GitHubActionsBuild-4g, PingShi-1g
kotlin.daemon.jvmargs=-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -XX:MaxMetaspaceSize=512m
#Kotlin/Native XiLieYuYan(IOSPingTai)
kotlin.native.ignoreDisabledTargets=true
#RuoYongLeK2
#kotlin.experimental.tryK2=true
# Kotlin/Native NeiCunGuanLiYouHua
kotlin.native.cacheDir=/.konan/cache

#Gradle
#Gradle-NeiCunFenPeiHuanJingBianLiang, GitHubActionsBuild-4g, PingShi-1g
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true


#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

#IOS-UIKit YuanShengKuaJiaZhiChi XuanXiang
org.jetbrains.compose.experimental.uikit.enabled=true


#Desktop ApplicationConfigFile Encoding (UTF-8 WeiJieJueDaBaoBaoMingZhongWenLuanMa)
systemProp.file.encoding=UTF-8

#Compose-MacOS ShiYanXingMuBiao (GengXinBan Compose Multiplatform XuYao XianShiQiYong)
org.jetbrains.compose.experimental.macos.enabled=true


#ksp.useKSP2=true
#LinShiJinYongZengLiangBianYiQiKanShiFouJieJue KSP YiChang: KSP failed with exit code: PROCESSING_ERROR
#ksp.incremental=false



#systemProp.http.proxyHost=127.0.0.1
#systemProp.http.proxyPort=10809
#systemProp.https.proxyHost=127.0.0.1
#systemProp.https.proxyPort=10809