platform :ios, '12.0'
use_frameworks!

target 'iosApp' do
   pod 'WechatOpenSDK', '2.0.4'   #添加微信SDK
#    pod 'TencentOpenAPI', '3.4.18.1' #添加QQSDK
   pod 'AlipaySDK-iOS', '15.8.30' #添加支付宝SDK
   pod 'OneSignalFramework', '~>5.0.0'#OneSignal实时接收推送唤醒已冻结进程-IOS版(支持国内外苹果APNs推送)
end
