name: 🔍 Tmate SSH (macOS Debug)

on:
  workflow_dispatch:   # 手动触发，需在默认分支上才能启动

jobs:
  debug:
    runs-on: macos-13   #GitHubActions免费计划提供macOS runner，只是并发数少，高峰期要排队，macos-14经常满载，用macos-旧版更容易排到
    timeout-minutes: 120
    steps:
      - name: 🛰️ 启动 Tmate SSH 会话
        uses: mxschmitt/action-tmate@v3
        with:
#          limit-access-to-actor: true   # 只有触发者本人能连接（更安全）
          timeout-minutes: 120          # 120分钟后自动断开
